app_product_delete :
    path: /product/new/delete/{path}
    controller: App\Controller\ProductController::deleteAction
    methods : GET|HEAD

app_product_delete_user :
    path: /product/new/deleteUser/{path}/{id}
    controller: App\Controller\ProductController::deleteUser
    methods: GET|HEAD

app_product_delete_dir :
    path: /product/new/deleteDir/{path}
    controller: App\Controller\ProductController::deleteActionDir
    methods: GET|HEAD

